version: "3.8"
services:
  backend:
    build:
      context: ./server
    container_name: server
    expose:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/history-db
    networks:
      - history-network

  mongo:
    image: mongo:4.4.29
    container_name: mongo
    ports:
      - "27018:27017"  # 可选，仅供本地连接调试
    volumes:
      - mongo-data:/data/db
    networks:
      - history-network

networks:
  history-network:
    driver: bridge

volumes:
  mongo-data: