version: "3.8"
services:
  backend:
    build:
      context: ./server
    container_name: server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DB_URI: mongodb://mongo:27017/history-db
    networks:
      - history-network

  frontend:
    build:
      context: ./web
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - history-network
    environment:
      REACT_APP_API_URL: http://backend:3000

  mongo:
    image: mongo:4.4.29
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - history-network

networks:
  history-network:
    driver: bridge
