version: "3.8"
services:
  backend:
    build:
      context: ./server
    container_name: server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DB_URI: mongodb://admin:admin@mongo:27017/timeline?tls=false&replicaSet=rs0&authSource=admin
      DB_NAME: timeline
      DB_USER: admin
      DB_PASS: admin
    networks:
      - history-network

  frontend:
    build:
      context: ./web
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - history-network
    environment:
      REACT_APP_API_URL: http://backend:3000

  mongo:
    image: mongo:4.4.29
    container_name: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: timeline
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always
    command: mongod --replSet rs0 --keyFile /data/keyfile --bind_ip_all
    volumes:
      - ./mongo-data:/data/db
      - ./keyFile:/data/keyfile
    networks:
      - history-network

networks:
  history-network:
    driver: bridge
