name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        TIMESTAMP=$(date +%s)
        docker build server --file server/Dockerfile --tag timeline-server:$TIMESTAMP
        docker save -o timeline-server-$TIMESTAMP.tar timeline-server:$TIMESTAMP
