name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies (Python + build tools)
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip build-essential

    - name: Build the Docker image
      run: docker build server --file server/Dockerfile --tag timeline-server:$(date +%s)
