name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        TIMESTAMP=$(date +%s)
        docker build server --file server/Dockerfile --tag timeline-server:$TIMESTAMP
        docker save -o timeline-server.tar timeline-server:$TIMESTAMP

    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: timeline-server.tar
        path: timeline-server.tar